### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'init')

### ISSUE THREAD

**Issue by malparty** [epaew/react-liff#333]
Hi,
Thanks for the great package! The stubbing, and ease of use seem really interesting!! :) 

I encounter an issue while following the README.md instruction. 

[Here is a repository to demo the issue](https://github.com/malparty/react-liff-issue-demo) with a blank `create-react-app` and the `react-liff` demo code. 

## The issue

| Logging the Error object | UI |
|---|---|
|![image](https://user-images.githubusercontent.com/77609814/140305683-784351a7-8884-4bb4-8c6f-80ce771f60c6.png)|![image](https://user-images.githubusercontent.com/77609814/140305701-cf7af4e4-d883-4ba9-9e54-5a01ff80e247.png)|

## Insights

It seems to be the import of `@line/liff` is the issue:
![image](https://user-images.githubusercontent.com/77609814/140306134-e802f391-aff6-47a4-9a1c-d7d2fcffeb05.png)

The `react-liff` package is fully working when I change this line:
`const liff = (_b = window.liff) !== null && _b !== void 0 ? _b : (yield Promise.resolve().then(() => __importStar(require('@line/liff')))).liff;`
into 
`const liff = (_b = window.liff) !== null && _b !== void 0 ? _b : (yield Promise.resolve().then(() => __importStar(require('@line/liff'))));`

As reference to the package source code, it corresponds to changing:
`const liff = window.liff ?? (await import('@line/liff')).liff;`
into
`const liff = window.liff ?? (await import('@line/liff'));`

(Context.tsx, l37)

> I also noticed that the type declarations provided by the `@line/liff` package are somehow misleading as they enable both `import { liff } from ...` and `import * as liff from ...` from type checking while only the latter seems to work.

Please let me know if you have an idea of the solution, or if the suggested changes make sense to you :) 

Many thanks for your support :)

**Comment by malparty** [comment]
Adding the deploy of the demo repo: https://react-liff-issue.netlify.app/ ;-)

**Comment by epaew** [comment]
Thank you for your report, @malparty.

I'm sorry, but currently the `react-liff` package only supports `@line/liff` versions from 2.9 to 2.13, as written in package.json.
https://github.com/epaew/react-liff/blob/86f157d1bbec35a170bb288200a64f690d75ef74/package.json#L54

The next release will support 2.14 and later versions. Please wait a little while.

**Comment by malparty** [comment]
Thanks for your quick answer :) 

My bad, I went too fast on the demo project. 
I confirm the issue still appears with versions 2.9, 2.10 and 2.13 of @line/liff (I only tried these 3 at the moment). 

-->  Demo repo updated in the [last commit](https://github.com/malparty/react-liff-issue-demo/commit/b5fdb839f54f759ff2e664757b582ce00ed44638).

**Comment by epaew** [comment]
Now, v1.2.1 was released. Please try it :)

**Comment by malparty** [comment]
Working super well! :) 

Many thanks for your speed in fixing that issue 🙌

![react-liff-working](https://user-images.githubusercontent.com/77609814/140449119-ba5a8489-b92f-4ff0-b0e3-5082c33b819a.gif)
